---

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: Redémarrer keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: Restart systemd-sysctl
  ansible.builtin.service:
    state: restarted
    name: systemd-sysctl

- name: Redémarrer systemd-sysctl
  ansible.builtin.service:
    state: restarted
    name: systemd-sysctl

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Vider les gestionnaires
  ansible.builtin.meta: flush_handlers

- name: Config file changed
  ansible.builtin.set_fact:
    rke2_restart_needed: true

- name: Fichier de configuration modifié
  ansible.builtin.set_fact:
    rke2_restart_needed: true

- name: Service (re)started
  ansible.builtin.set_fact:
    rke2_restart_needed: false

- name: Service (re)démarré
  ansible.builtin.set_fact:
    rke2_restart_needed: false
