---
- name: Reboot rke2_cluster
  hosts: all
  gather_facts: true
  serial: 1
  tasks:
    - name: Reboot the nodes (and Wait upto 5 mins max)
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 300
