galaxy_info:
  role_name: rke2
  author: Michal Muransky
  namespace: lablabs
  description: Ce rôle Ansible déploiera Rancher RKE2 Kubernetes
  company: Labyrinth Labs

  license: MIT

  min_ansible_version: 2.10.0

  platforms:
  - name: EL
    versions:
      - "8"
  - name: Ubuntu
    versions:
    - bionic
    - focal

  galaxy_tags:
    - kubernetes
    - k8s
    - rke2
    - rancher

dependencies: []
