---
- name: Pr√©parer
  hosts: node*
  become: true
  tasks:
    - name: Installer wget pour Ubuntu
      ansible.builtin.package:
        update_cache: true
        name:
          - wget
      when: ansible_distribution == "Ubuntu"

    - name: Installer iproute pour RockyLinux
      ansible.builtin.package:
        update_cache: true
        name:
          - iproute
      when: ansible_distribution == "Rocky"
