---
rke2_version: v1.34.1+rke2r1
rke2_ha_mode: true
rke2_ha_mode_keepalived: false
rke2_api_ip: 192.168.1.110
rke2_download_kubeconf: true
rke2_download_kubeconf_path: ./
rke2_ingress_default_cert: ""
rke2_ingress_default_cert_key: ""

# Configuration explicite des CIDRs pour Ã©viter les conflits Calico/Canal
rke2_cluster_cidr:
  - 10.42.0.0/16
rke2_service_cidr:
  - 10.43.0.0/16