---
rke2_version: v1.34.1+rke2r1
rke2_ha_mode: true
rke2_api_ip: 192.168.1.203
rke2_download_kubeconf: true
rke2_download_kubeconf_path: ./
rke2_custom_registry_configs:
 - endpoint: "harbor.devsecops-p-01-app.mondomaine.fr"
   config:
    tls:
     insecure_skip_verify: true
rke2_server_node_taints:
 - 'CriticalAddonsOnly=true:NoExecute'
rke2_ingress_default_cert: ""
rke2_ingress_default_cert_key: ""