---
- name: Créer le groupe etcd
  ansible.builtin.group:
    name: etcd
    state: present

- name: Créer l'utilisateur etcd
  ansible.builtin.user:
    name: etcd
    shell: /bin/nologin
    group: etcd
    comment: etcd user
    state: present

- name: Copier le fichier de configuration systemctl pour le durcissement du noyau
  ansible.builtin.copy:
    src: "{{ '/usr/local/share/rke2/rke2-cis-sysctl.conf' if (not usr_local.stat.writeable) or (partition_result.rc == 1) else '/opt/rke2/share/rke2/rke2-cis-sysctl.conf' }}"
    dest: /etc/sysctl.d/60-rke2-cis.conf
    mode: 0600
    remote_src: true
  notify: Restart systemd-sysctl

- name: Vider les gestionnaires
  ansible.builtin.meta: flush_handlers
