---
- name: Condamner et drainer le nœud {{ rke2_node_name }}
  ansible.builtin.shell: |
    set -o pipefail
    {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml \
    cordon "{{ rke2_node_name }}" && \
    {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml \
    drain "{{ rke2_node_name }}" --ignore-daemonsets --delete-emptydir-data {{ rke2_drain_additional_args }}
  args:
    executable: /bin/bash
  register: drain
  until:
    - drain.stdout is search('drained')
  retries: 100
  delay: 15
  changed_when: false
  delegate_to: "{{ active_server | default(groups[rke2_servers_group_name].0) }}"
  run_once: true
  when: rke2_drain_node_during_upgrade

- name: Redémarrer le service RKE2 sur {{ rke2_node_name }}
  ansible.builtin.service:
    name: "{{ rke2_service_name }}"
    state: restarted
  notify: "Service (re)started"

- name: Attendre que tous les nœuds soient à nouveau prêts
  ansible.builtin.shell: |
    set -o pipefail
    {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes | grep " Ready" | wc -l
  args:
    executable: /bin/bash
  changed_when: false
  register: all_ready_nodes
  until:
    - groups[rke2_cluster_group_name] | length == all_ready_nodes.stdout | int
  retries: 100
  delay: 15
  delegate_to: "{{ active_server | default(groups[rke2_servers_group_name].0) }}"
  run_once: true

- name: Lever la condamnation du nœud {{ rke2_node_name }}
  ansible.builtin.shell: |
    set -o pipefail
    {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml \
    uncordon "{{ rke2_node_name }}"
  args:
    executable: /bin/bash
  changed_when: false
  delegate_to: "{{ active_server | default(groups[rke2_servers_group_name].0) }}"
  run_once: true
  when: rke2_drain_node_during_upgrade

- name: Attendre que tous les pods soient à nouveau prêts
  ansible.builtin.shell: |
    set -o pipefail
    {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get pods -A --field-selector=status.phase!=Running,status.phase!=Succeeded --ignore-not-found | wc -l
  args:
    executable: /bin/bash
  changed_when: false
  register: all_pods_ready
  until:
    '"0" in all_pods_ready.stdout'
  retries: 100
  delay: 15
  delegate_to: "{{ active_server | default(groups[rke2_servers_group_name].0) }}"
  run_once: true
  when: rke2_wait_for_all_pods_to_be_ready

- name: Attendre que tous les pods passent les vérifications de disponibilité
  ansible.builtin.shell: |
    {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml wait {{ rke2_wait_for_all_pods_to_be_healthy_args }}
  args:
    executable: /bin/bash
  changed_when: false
  retries: 100
  delay: 15
  delegate_to: "{{ active_server | default(groups[rke2_servers_group_name].0) }}"
  run_once: true
  when: rke2_wait_for_all_pods_to_be_healthy
