---
- name: Résumé
  when: inventory_hostname == groups[rke2_servers_group_name].0
  block:
    - name: Préparer le résumé
      ansible.builtin.shell: |
        set -e
        {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes -o wide --show-labels
      args:
        executable: /bin/bash
      changed_when: false
      retries: 5
      register: nodes_summary

    - name: État des nœuds K8s
      ansible.builtin.debug:
        var: nodes_summary.stdout_lines
