---
rke2_version: v1.34.1+rke2r1
rke2_ha_mode: true
rke2_api_ip: 192.168.1.200
rke2_download_kubeconf: true
rke2_download_kubeconf_path: ./
rke2_ingress_default_cert: ""
rke2_ingress_default_cert_key: ""